import Card from "./Card";
import { useState, useEffect } from "react";
import { db } from "@/firebase";
import { collection, onSnapshot, orderBy, query } from "firebase/firestore";

function Explore() {
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    const unsubscribe = onSnapshot(
      query(collection(db, "posts"), orderBy("timestamp", "desc")),
      (snapshot) => {
        setPosts(snapshot.docs);
      }
    );
    return unsubscribe;
  }, [db]);

  return (
    <div className="max-w-6xl mt-5 mx-auto dark:bg-black dark:text-white">
      <p className="font-montserrat text-md mt-20 text-[#666e75]">
        Browse through a collection of imaginative and visually stunning images
        generated by Creativegram
      </p>
      <hr className="border-gray-500 my-5"></hr>

      <div className="grid lg:grid-cols-4 py-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-1">
        {posts.map((post) => (
          <Card
            key={post.id}
            id={post.id}
            username={post.data().username}
            userImg={post.data().profileImg}
            img={post.data().image}
            caption={post.data().caption}
          />
        ))}
      </div>
    </div>
  );
}

export default Explore;
