import Head from "next/head";
import UserProfile from "@/components/UserProfile";

export default function Profile() {
  return (
    <div className="">
      <Head>
        <title>Creativegram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* UserProfile */}
      <UserProfile />
    </div>
  );
}
