import Head from "next/head";
import Header from "@/components/Header";
import Modal from "@/components/Modal";
import Explore from "@/components/Explore";

function Community() {
  return (
    <div className="dark:bg-black text-white">
      <Head>
        <title>Creativegram</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      <Explore />
      <Modal />
    </div>
  );
}

export default Community;
